# DEBUG - to be changed
# baseurl: /dosbox-x

### Site parameters ###

# Name of site shown in header
name: DOSBox-X
# Site tagline in the header
# NTS: This should be description in vanila Slate, but who cares.
tagline: "Cross-platform DOS emulation package<br />Complete, accurate emulation and more"
# The theme is heavily edited, so this is not relevant anymore
# theme: jekyll-theme-slate

# Title for pages without a custom title
# The default preference is:
# Page title -> layout title -> global title
title: "DOSBox-X - Complete DOS emulation package"
# SEO meta tags
seo:
  description: "DOSBox-X: Free, cross-platform and complete DOS, Windows 3.x and 9x emulation package"

### End site params ###

# TIP: These are only the basic things.
# More Jekyll-related stuff can be found at https://jekyllrb.org
# If you want to test offline, run jekyll serve
# (install Jekyll CLI first)

# To add a version onto this site (can't figure out where to put this, but anyway):
# 1. Edit _data/version_lst.yml - add a entry to versions array,
# (remember that the version array must in the order of older->newer)
# change parameters in _data/latest_version.yml too if added version is latest.
# Also change last to a older version than the version you're adding (nothing if none)
# if you're adding the version specified in last. (last is a placeholder string)
# The added version will show up in /release-notes.
# 2. Copy the latest release notes file as a template for your new one,
# and rename it to release-{new version string}.html.
# Change the front matter if needed. Then write relnote.
# Link for added version in /release-notes should not 404;
# If added is latest, /release-notes will show that and relnote page
# won't link to latest relnote or display a error.
# If not, refresh and refresh or try again.
# 3. Finally, edit the link sidebar: _includes/version.html if added version is latest
# 4 JON: update the compat report files (optional)
# 5. use doxygen to generate docs (optional)
# 6. edit the wiki (optional)
# Pages will be automatically updated if needed
